// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateAuthors = `-- name: BatchCreateAuthors :batchexec
insert into authors(
    name)
values (
    $1)
`

type BatchCreateAuthorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) BatchCreateAuthors(ctx context.Context, name []string) *BatchCreateAuthorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchCreateAuthors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateAuthorsBatchResults{br, len(name), false}
}

func (b *BatchCreateAuthorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateAuthorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
