// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type Author struct {
	ID   int32
	Name string
}

type AuthorsBook struct {
	AuthorID int32
	BookID   int32
}

type Book struct {
	ID    int32
	Title string
}
